apiVersion: app.fybrik.ibm.com/v1alpha1
kind: FybrikModule
metadata:
  name: arrow-flight-module
  labels:
    name: arrow-flight-module
    version: latest  # semantic version
spec:
  chart:
    name: ghcr.io/fybrik/arrow-flight-module-chart:latest
    values:
      image.tag: latest
  flows:
    - read
  capabilities:
    api:
      endpoint:
        port: 80
        scheme: grpc
      protocol: fybrik-arrow-flight
      dataformat: arrow
    supportedInterfaces:
    - flow: read
      source:
        protocol: s3
        dataformat: parquet
    - flow: read
      source:
        protocol: s3
        dataformat: csv
    - flow: write
      sink:
        protocol: s3
        dataformat: parquet
    actions:
      - id: redact-ID
        level: 2  # column
      - id: removed-ID
        level: 2  # column
